({
	yoffset: -1,
	zoffset: -1,
	repeat: true,
	blocks: [
		[
			['cobble', 'cobble', 'cobble'],
			['cobble', 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
		],
		[
			['cobble', 'cobble', 'cobble'],
			['cobble', 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
		],
		[
			['cobble', 'cobble', 'cobble'],
			['cobble', 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
		],
		[
			['cobble', 'cobble', 'cobble'],
			['cobble', 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
		],
		[
			['cobble', 'cobble', 'cobble'],
			['cobble', 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
			[        , 'cobble', 'cobble'],
		]
	]
});
