# find bullet headers and libraries

SET( BULLETDIR $ENV{BULLETDIR} ) 
  
FIND_PATH(BULLET_INCLUDE_DIR btBulletDynamicsCommon.h
	/usr/include
	/usr/local/include
	$ENV{INCLUDE}
	${BULLETDIR}/src
)

SET( _BULLET_LIBRARIES BulletCollision BulletDynamics LinearMath )

FOREACH( l ${_BULLET_LIBRARIES} )
	MESSAGE(STATUS BULLET_LIBRARY_${l})
	FIND_LIBRARY(BULLET_LIBRARY_${l}
		NAMES ${l}
		PATHS
		/usr/lib
		/usr/local/lib
		${BULLETDIR}/lib
	)
	SET( BULLET_LIBRARY ${BULLET_LIBRARY} ${BULLET_LIBRARY_${l}} )
ENDFOREACH( l )

IF(BULLET_INCLUDE_DIR)
	MESSAGE(STATUS "Found Bullet include dir: ${BULLET_INCLUDE_DIR}")
ELSE(BULLET_INCLUDE_DIR)
	MESSAGE(STATUS "Could NOT find Bullet headers.")
ENDIF(BULLET_INCLUDE_DIR)

IF(BULLET_LIBRARY)
	MESSAGE(STATUS "Found Bullet library: ${BULLET_LIBRARY}")
ELSE(BULLET_LIBRARY)
	MESSAGE(STATUS "Could NOT find Bullet library.")
ENDIF(BULLET_LIBRARY)

IF(BULLET_INCLUDE_DIR AND BULLET_LIBRARY)
	SET(BULLET_FOUND TRUE CACHE STRING "True if Bullet was found")
ELSE(BULLET_INCLUDE_DIR AND BULLET_LIBRARY)
	SET(BULLET_FOUND FALSE)
IF(BULLET_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find Bullet. Please install Bullet (http://bulletphysics.org/wordpress/)")
	ENDIF(BULLET_FIND_REQUIRED)
ENDIF(BULLET_INCLUDE_DIR AND BULLET_LIBRARY)
